-- CreateEnum
CREATE TYPE "ResultadoComercial" AS ENUM ('ABIERTO', 'GANADO', 'PERDIDO_COMPUTABLE', 'NO_COMPUTABLE');

-- CreateEnum
CREATE TYPE "MotivoCierre" AS ENUM ('PRECIO', 'PLAZO_ENTREGA', 'FORMA_PAGO', 'ELIGIO_COMPETENCIA', 'PROPUESTA_TECNICA_NO_ADECUADA', 'FALTA_SEGUIMIENTO', 'CLIENTE_NO_RESPONDE', 'ERROR_PRESUPUESTO', 'LICITACION_NO_EJECUTADA', 'LICITACION_NO_ADJUDICADA', 'OBRA_CANCELADA', 'OBRA_SUSPENDIDA', 'PRESUPUESTO_REFERENCIA', 'PRESUPUESTO_DUPLICADO', 'CLIENTE_FUERA_PERFIL', 'PROYECTO_SIN_DECISION_REAL', 'OTRO');

-- CreateEnum
CREATE TYPE "TipoOportunidad" AS ENUM ('OBRA_REAL', 'LICITACION', 'PRESUPUESTO_COMPARATIVO', 'ADICIONAL_REPOSICION', 'PROYECTO_EN_ANALISIS', 'OTRO');

-- AlterTable
ALTER TABLE "Presupuesto" ADD COLUMN     "comentarioCierre" TEXT,
ADD COLUMN     "fechaCierreComercial" TIMESTAMP(3),
ADD COLUMN     "fechaPrimerEnvio" TIMESTAMP(3),
ADD COLUMN     "fechaUltimaActividadComercial" TIMESTAMP(3),
ADD COLUMN     "motivoCierre" "MotivoCierre",
ADD COLUMN     "resultadoComercial" "ResultadoComercial" NOT NULL DEFAULT 'ABIERTO',
ADD COLUMN     "tipoOportunidad" "TipoOportunidad";